platform :ios, '7.0'

pod 'AFNetworking', '~>2.0.1'
pod 'AFNetworking/UIKit'
pod 'TDAudioPlayer', :git => 'https://github.com/tonyd256/TDAudioPlayer'
pod 'TestFlightSDK', '2.1.1-beta'

target 'Console.fmTests', :exclusive => true do
    pod 'Kiwi', '~> 2.2.1'
    pod 'OHHTTPStubs', '~> 2.0.0'
end
