platform :ios, '7.0'

pod 'AFNetworking', '2.0.0-RC3'
pod 'AFNetworking/UIKit+AFNetworking'

target 'Console.fmTests', :exclusive => true do
    pod 'Kiwi', '~> 2.2.1'
    pod 'OHHTTPStubs', '~> 2.0.0'
end
